name: IDX AI Agent

on:
  schedule:
    - cron: '0 1,3,4,8 * * *' # 08, 10, 11, 15 WIB
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

